export const BEFORE_DEPTB_STATE = "BEFORE_DEPTB_STATE";
export const FETCH_DEPTB = "FETCH_DEPTB";
export const FETCH_DEPTB_ERROR = "FETCH_DEPTB_ERROR";
export const FORWARD_DEPTB = "FORWARD_DEPTB";
export const FORWARD_DEPTB_ERROR = "FORWARD_DEPTB_ERROR";
