export const BEFORE_DEPTC_STATE = "BEFORE_DEPTC_STATE";
export const FETCH_DEPTC = "FETCH_DEPTC";
export const FETCH_DEPTC_ERROR = "FETCH_DEPTC_ERROR";
export const FORWARD_DEPTC = "FORWARD_DEPTC";
export const FORWARD_DEPTC_ERROR = "FORWARD_DEPTC_ERROR";
