export const BEFORE_DEPTA_STATE = "BEFORE_DEPTA_STATE";
export const DELETE_DEPTA_SUCCESS = "CREATE_DEPTA_SUCCESS";
export const DELETE_DEPTA_ERROR = "CREATE_DEPTA_ERROR";
export const FETCH_DEPTA = "FETCH_DEPTA";
export const FETCH_DEPTA_ERROR = "FETCH_DEPTA_ERROR";
